fix paths

diff --git a/.github/actions/create-package/action.yml b/.github/actions/create-package/action.yml
--- a/.github/actions/create-package/action.yml
+++ b/.github/actions/create-package/action.yml
@@ -31,12 +31,12 @@ runs:
         echo "::group::>Debug build"
         cmake --build . --config Debug
         echo
-        readelf -d Debug/*.so || echo "readelf failed"
+        readelf -d Debug/*.so* || echo "readelf failed"
         echo "::endgroup::"
         echo "::group::>Release build"
         cmake --build . --config Release
         echo
-        readelf -d Release/*.so || echo "readelf failed"
+        readelf -d Release/*.so* || echo "readelf failed"
         echo "::endgroup::"
 
         echo "::group::>Packaging"
@@ -55,13 +55,13 @@ runs:
         cmake --build . --config Release --target install > ../packages/install-manifests/install-release.log
         cp install_manifest.txt                             ../packages/install-manifests/install_manifest-release.txt
         cmake --build . --config Debug --target install >   ../packages/install-manifests/install-debug2.log
-        # this installs to "C:/Program Files (x86)/OGDF-PROJECT" on windows
+        # this installs to "C:/Program Files (x86)/OGDF-PROJECT" on windows and to "/usr/local/lib/" on linux
+        { readelf -d /usr/local/lib/*.so* || echo "failed $?"; } > ../packages/install-manifests/readelf.txt
 
     - name: Test Installed Package
       uses: ./.github/actions/test-installed-package
       with:
-        bin_path: "C:/Program Files (x86)/OGDF-PROJECT/bin"
-        exc_special_path: "${{ github.workspace }}/doc/examples/special"
+        exc_special_path: "../doc/examples/special"
         cmake_test_args: "${{ inputs.cmake_test_args }}"
 
     - name: Store packages
diff --git a/.github/actions/test-installed-package/action.yml b/.github/actions/test-installed-package/action.yml
--- a/.github/actions/test-installed-package/action.yml
+++ b/.github/actions/test-installed-package/action.yml
@@ -1,9 +1,7 @@
 name: 'Test Installed Package'
 inputs:
-  bin_path:
-    description: "absolute path to binary install directory for windows"
   exc_special_path:
-    description: "absolute path to doc/examples/special"
+    description: "path to doc/examples/special"
   cmake_test_args:
     description: "string"
 
@@ -13,18 +11,35 @@ runs:
     - name: Test installed build results
       shell: bash
       run: |
-        set -x
         mkdir build-test && cd build-test
         export CCACHE_BASEDIR="$(pwd)"
-        export PATH="${{ inputs.bin_path }}:$PATH" #windows
-        echo "$PATH"
-        cmake ${{ inputs.exc_special_path }} --debug-find ${{ inputs.cmake_test_args }}
 
+        mkdir debug-info
+        { ld --verbose || echo "failed $?"; } > debug-info/ld.txt
+        { gcc -print-search-dirs || echo "failed $?"; } > debug-info/gcc.txt
+        { ldconfig -v || echo "failed $?"; } > debug-info/ldconfig.txt
+        { readelf -d /usr/local/lib/*.so || echo "failed $?"; } > debug-info/readelf.txt
+        echo "::group::>Environment"
+        env
+        echo "::endgroup::"
+        echo "::group::>CMake"
+        cmake ${{ inputs.exc_special_path }} --debug-find ${{ inputs.cmake_test_args }}
+        echo "::endgroup::"
+
+        echo "::group::>Debug build"
         cmake --build . --config Debug
+        echo
+        readelf -d Debug/check-build-mode || echo "readelf failed"
+        echo "::endgroup::"
+        echo "::group::>Release build"
         cmake --build . --config Release
+        echo
+        readelf -d Release/check-build-mode || echo "readelf failed"
+        echo "::endgroup::"
 
         has_error=0
         run_executable() {
+            sync
             local path="$1"
 
             if [[ ! -x "$path" ]]; then
@@ -42,6 +57,7 @@ runs:
             if [[ $exit_code -ne 0 ]]; then
                 has_error=1
             fi
+            sync
         }
 
         run_executable "Release/check-build-mode${{ runner.os == 'Windows' && '.exe' || '' }}"
@@ -56,9 +72,7 @@ runs:
     - name: Try running directly on windows
       shell: pwsh
       run: |
-        $env:PATH += ";${{ inputs.bin_path }}"
         echo $env:PATH
-        
         $script:hasError = $false
         
         function Run-Executable {
